const KEY='pollitos_cespedes_v2';
const LEGACY_KEY='pollitos_cespedes_mvp';
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const money=n=>new Intl.NumberFormat('es-DO',{style:'currency',currency:'DOP'}).format(Number(n||0));
const fmtDate=d=>new Intl.DateTimeFormat('es-DO',{dateStyle:'short',timeStyle:'short'}).format(new Date(d));
const dateOnly=d=>new Date(d).toISOString().slice(0,10);
const todayKey=()=>dateOnly(new Date());
const startOfWeek=()=>{const d=new Date();const day=d.getDay()||7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day+1);return d};
const startOfMonth=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)};
const defaults={products:[{id:'color',name:'Pollitos de Color',price:50,costPrice:0,stock:0},{id:'engorde',name:'Pollitos de Engorde',price:50,costPrice:0,stock:0}],clients:[],sales:[],payments:[],stockMovements:[],denominations:[1,5,10,25,50,100,200,500,1000,2000].map(value=>({value,count:0}))};
let state=loadState();let installPrompt=null;let clientDialogSource='clients';
function loadState(){return structuredClone(defaults)}
function save(){renderAll();queueDatabaseSave()}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),2200)}
function go(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById('view-'+view)?.classList.add('active');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'});if(view==='sale')prepareSale();if(view==='reports')renderReports()}
const productById=id=>state.products.find(p=>p.id===id);
const clientById=id=>state.clients.find(c=>c.id===id);
const productName=id=>productById(id)?.name||'Producto eliminado';
const clientName=(id,sale=null)=>{if(id){const c=clientById(String(id));if(c?.name)return c.name}const snapshot=String(sale?.clientSnapshot||sale?.clientName||sale?.customerName||'').trim();return snapshot||(id?'Cliente eliminado':'Sin cliente')};
const saleSubtotal=s=>Number(s.qty)*Number(s.price);
const saleTransport=s=>Number(s.transport||0);
const saleTotal=s=>saleSubtotal(s)+saleTransport(s);
const saleCost=s=>Number(s.qty)*Number(s.costPriceSnapshot||0);
const saleProfit=s=>saleTotal(s)-saleCost(s);
const paymentExtras=s=>state.payments.filter(p=>p.saleId===s.id).reduce((a,p)=>a+Number(p.amount||0),0);
const salePaid=s=>Number(s.paid||0)+paymentExtras(s);
const salePending=s=>Math.max(0,saleTotal(s)-salePaid(s));
const cashTotal=()=>state.denominations.reduce((a,d)=>a+Number(d.value)*Number(d.count||0),0);
let saleCashCounts={};
const saleCashAmount=()=>Object.entries(saleCashCounts).reduce((a,[value,count])=>a+Number(value)*Number(count||0),0);
function cashMapFromSale(s){return s?.cashDenominations&&typeof s.cashDenominations==='object'?{...s.cashDenominations}:{}}
function applyCashMap(map,multiplier=1){Object.entries(map||{}).forEach(([value,count])=>{const d=state.denominations.find(x=>Number(x.value)===Number(value));if(d)d.count=Math.max(0,Number(d.count||0)+(Number(count||0)*multiplier))})}
function saleCashCard(value){const count=Number(saleCashCounts[value]||0);return `<div class="denom-card"><div class="denom-top"><strong>${money(value)}</strong><span>${money(value*count)}</span></div><small>${count} ${count===1?'pieza':'piezas'}</small><div class="denom-controls"><button type="button" data-sale-denom-minus="${value}">−</button><input type="number" min="0" step="1" inputmode="numeric" value="${count}" data-sale-denom="${value}" aria-label="Cantidad de ${value}"/><button type="button" data-sale-denom-plus="${value}">+</button></div></div>`}
function renderSaleCash(){const section=document.getElementById('saleCashSection');if(!section)return;const method=document.getElementById('salePayment').value,paid=Number(document.getElementById('salePaid').value||0);const visible=method==='cash'&&paid>0;section.classList.toggle('hidden',!visible);if(!visible)return;const values=state.denominations.map(d=>Number(d.value)).sort((a,b)=>b-a);document.getElementById('saleCashGrid').innerHTML=values.map(saleCashCard).join('');const counted=saleCashAmount();document.getElementById('saleCashCounted').textContent=money(counted);document.getElementById('saleCashExpected').textContent=money(paid);const status=document.getElementById('saleCashStatus'),diff=Math.round((counted-paid)*100)/100;status.className='cash-sale-status '+(Math.abs(diff)<.01?'ok':'pending');status.textContent=Math.abs(diff)<.01?'✓ Denominaciones completas':counted<paid?`Faltan ${money(paid-counted)}`:`Sobran ${money(counted-paid)}`}
const totalStock=()=>state.products.reduce((a,p)=>a+Number(p.stock||0),0);
function salesBetween(from,to){const a=new Date(from);a.setHours(0,0,0,0);const b=new Date(to);b.setHours(23,59,59,999);return state.sales.filter(s=>{const d=new Date(s.date);return d>=a&&d<=b})}
function renderDashboard(){const today=salesBetween(new Date(),new Date());const month=salesBetween(startOfMonth(),new Date());document.getElementById('todaySales').textContent=money(today.reduce((a,s)=>a+saleTotal(s),0));document.getElementById('todayUnits').textContent=today.reduce((a,s)=>a+Number(s.qty),0);document.getElementById('cashOnHand').textContent=money(cashTotal());document.getElementById('cashOnHand2').textContent=money(cashTotal());document.getElementById('stockTotal').textContent=totalStock();document.getElementById('pendingTotal').textContent=money(state.sales.reduce((a,s)=>a+salePending(s),0));document.getElementById('monthSales').textContent=money(month.reduce((a,s)=>a+saleTotal(s),0));document.getElementById('monthUnits').textContent=month.reduce((a,s)=>a+Number(s.qty),0)+' unidades';document.getElementById('dashboardStock').innerHTML=state.products.map(p=>`<article class="list-item"><div><strong>${p.name}</strong><div class="meta">${money(p.price)} c/u</div></div><span class="inventory-badge ${p.stock<=10?'low':''}">${p.stock} disponibles</span></article>`).join('')||'<div class="empty-state">Sin productos.</div>';const recent=[...state.sales].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,5);document.getElementById('recentSales').innerHTML=recent.length?recent.map(s=>saleCard(s,false)).join(''):'Todavía no hay ventas.'}
function saleCard(s,actions=true){const pending=salePending(s);return `<article class="list-item"><div><strong>${clientName(s.clientId,s)}</strong><div class="meta">${productName(s.productId)} · ${s.qty} unid. · ${fmtDate(s.date)}</div><div class="meta">Pollitos: ${money(saleSubtotal(s))}${saleTransport(s)>0?` · Transporte: ${money(saleTransport(s))}`:''}</div><div class="meta">Cobrado: ${money(salePaid(s))}${pending>0?` · <span class="negative">Pendiente: ${money(pending)}</span>`:' · <span class="positive">Pagada</span>'}</div></div><div><div class="amount">${money(saleTotal(s))}</div>${actions?`<div class="item-actions">${pending>0?`<button class="mini-btn pay" data-pay="${s.id}">Abonar</button>`:''}<button class="mini-btn" data-edit-sale="${s.id}">Editar</button><button class="mini-btn danger" data-del-sale="${s.id}">Eliminar</button></div>`:''}</div></article>`}
function renderHistory(){const q=(document.getElementById('historySearch')?.value||'').toLowerCase();const f=document.getElementById('historyFilter')?.value||'all';let sales=[...state.sales].sort((a,b)=>new Date(b.date)-new Date(a.date));sales=sales.filter(s=>(clientName(s.clientId,s)+' '+productName(s.productId)).toLowerCase().includes(q));if(f==='pending')sales=sales.filter(s=>salePending(s)>0);if(f==='paid')sales=sales.filter(s=>salePending(s)<=0);document.getElementById('salesHistory').innerHTML=sales.length?sales.map(s=>saleCard(s,true)).join(''):'<div class="panel empty-state">No hay ventas para mostrar.</div>'}
function renderClients(){const q=(document.getElementById('clientSearch')?.value||'').toLowerCase();const clients=[...state.clients].filter(c=>(c.name+' '+c.phone).toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name));document.getElementById('clientsList').innerHTML=clients.length?clients.map(c=>{const ss=state.sales.filter(s=>s.clientId===c.id);const total=ss.reduce((a,s)=>a+saleTotal(s),0),pending=ss.reduce((a,s)=>a+salePending(s),0);return `<article class="list-item"><div><strong>${c.name}</strong><div class="meta">${c.phone||'Sin teléfono'} · ${ss.length} ventas</div><div class="meta">Comprado: ${money(total)}${pending?` · <span class="negative">Debe: ${money(pending)}</span>`:''}</div></div><div class="item-actions"><button class="mini-btn" data-edit-client="${c.id}">Editar</button><button class="mini-btn danger" data-del-client="${c.id}">Eliminar</button></div></article>`}).join(''):'<div class="panel empty-state">No hay clientes.</div>'}
function renderInventory(){document.getElementById('inventoryTotal').textContent=totalStock();document.getElementById('inventoryValue').textContent=money(state.products.reduce((a,p)=>a+Number(p.stock||0)*Number(p.costPrice||0),0));document.getElementById('inventoryList').innerHTML=state.products.map(p=>`<article class="inventory-card"><div class="inventory-main"><div><span class="product-dot">🐥</span><strong>${p.name}</strong><div class="meta">Compra: ${money(p.costPrice||0)} · Venta: ${money(p.price)}</div></div><div class="stock-number"><strong>${p.stock}</strong><span>disponibles</span></div></div><div class="inventory-actions"><button class="secondary small" data-stock-minus="${p.id}">− 1</button><button class="primary small" data-edit-stock="${p.id}">Editar cantidad</button><button class="secondary small" data-stock-plus="${p.id}">+ 1</button></div></article>`).join('');const movements=[...state.stockMovements].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,20);document.getElementById('stockMovementsList').innerHTML=movements.length?movements.map(m=>`<article class="list-item"><div><strong>${Number(m.qty)>0?'+':''}${m.qty} · ${productName(m.productId)}</strong><div class="meta">${fmtDate(m.date)}${m.costPrice!==undefined?` · Compra ${money(m.costPrice)} c/u · Total ${money(Number(m.qty)*Number(m.costPrice))}`:''}${m.note?' · '+m.note:''}</div></div></article>`).join(''):'<div class="empty-state">Aún no hay movimientos de inventario.</div>';document.getElementById('stockProduct').innerHTML=state.products.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}
function denomCard(d,i){return `<div class="denom-card"><div class="denom-top"><strong>${money(d.value)}</strong><span>${money(d.count*d.value)}</span></div><small>${d.count} ${d.count===1?'pieza':'piezas'}</small><div class="denom-controls"><button type="button" data-denom-minus="${i}" aria-label="Restar">−</button><input type="number" min="0" step="1" inputmode="numeric" value="${d.count}" data-denom="${i}" aria-label="Cantidad de ${d.value}"/><button type="button" data-denom-plus="${i}" aria-label="Sumar">+</button></div></div>`}
function renderMoney(){const total=cashTotal(),bills=state.denominations.map((d,i)=>({...d,i})).filter(d=>d.value>=50).sort((a,b)=>b.value-a.value),coins=state.denominations.map((d,i)=>({...d,i})).filter(d=>d.value<50).sort((a,b)=>b.value-a.value);document.getElementById('moneyTotal').textContent=money(total);document.getElementById('billsTotal').textContent=money(bills.reduce((a,d)=>a+d.value*d.count,0));document.getElementById('coinsTotal').textContent=money(coins.reduce((a,d)=>a+d.value*d.count,0));document.getElementById('billsGrid').innerHTML=bills.map(d=>denomCard(d,d.i)).join('');document.getElementById('coinsGrid').innerHTML=coins.map(d=>denomCard(d,d.i)).join('');const used=state.denominations.filter(d=>d.count>0).sort((a,b)=>b.value-a.value);document.getElementById('moneyBreakdown').innerHTML=used.length?used.map(d=>`<article class="list-item"><span>${d.count} × ${money(d.value)}</span><strong>${money(d.count*d.value)}</strong></article>`).join(''):'<div class="empty-state">Aún no has contado efectivo.</div>'}
function renderProducts(){document.getElementById('productsList').innerHTML=state.products.map(p=>`<article class="list-item"><div><strong>${p.name}</strong><div class="meta">Inventario: ${p.stock} · Compra: ${money(p.costPrice||0)}</div></div><div><strong class="amount">${money(p.price)}</strong><div class="item-actions"><button class="mini-btn" data-edit-product="${p.id}">Editar</button>${state.products.length>1?`<button class="mini-btn danger" data-del-product="${p.id}">Eliminar</button>`:''}</div></div></article>`).join('')}
function renderSaleSelectors(){const cust=document.getElementById('saleCustomer');const selected=cust.value;cust.innerHTML='<option value="">Venta sin cliente</option>'+state.clients.sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${c.id}">${c.name}</option>`).join('');cust.value=selected;const prod=document.getElementById('saleProduct'),sel=prod.value;prod.innerHTML=state.products.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');prod.value=state.products.some(p=>p.id===sel)?sel:(state.products[0]?.id||'');updateStockHint()}
function prepareSale(){renderSaleSelectors();const id=document.getElementById('saleId').value;if(!id){const p=productById(document.getElementById('saleProduct').value);document.getElementById('salePrice').value=p?.price??50;document.getElementById('saleQty').value=1;document.getElementById('salePaid').value=0;document.getElementById('saleTransport').value=0;document.getElementById('saleNote').value='';}updateSalePreview();updateStockHint()}
function updateStockHint(){const p=productById(document.getElementById('saleProduct').value);let available=Number(p?.stock||0);const editId=document.getElementById('saleId').value;if(editId){const old=state.sales.find(s=>s.id===editId);if(old&&old.productId===p?.id)available+=Number(old.qty)}document.getElementById('saleStockHint').textContent=available}
function updateSalePreview(){const qty=Number(document.getElementById('saleQty').value||0),price=Number(document.getElementById('salePrice').value||0),transport=Number(document.getElementById('saleTransport').value||0);document.getElementById('saleTotalPreview').textContent=money(qty*price+transport)}
function reportRange(){const p=document.getElementById('reportPeriod').value;const now=new Date();if(p==='today')return [now,now];if(p==='week')return [startOfWeek(),now];if(p==='month')return [startOfMonth(),now];const f=document.getElementById('reportFrom').value,t=document.getElementById('reportTo').value;return [f?new Date(f):startOfMonth(),t?new Date(t):now]}
function reportSales(){const [from,to]=reportRange();return salesBetween(from,to)}
function renderReports(){const sales=reportSales();document.getElementById('reportSales').textContent=money(sales.reduce((a,s)=>a+saleTotal(s),0));document.getElementById('reportTransport').textContent=money(sales.reduce((a,s)=>a+saleTransport(s),0));document.getElementById('reportCost').textContent=money(sales.reduce((a,s)=>a+saleCost(s),0));document.getElementById('reportProfit').textContent=money(sales.reduce((a,s)=>a+saleProfit(s),0));document.getElementById('reportUnits').textContent=sales.reduce((a,s)=>a+Number(s.qty),0);document.getElementById('reportPaid').textContent=money(sales.reduce((a,s)=>a+salePaid(s),0));document.getElementById('reportPending').textContent=money(sales.reduce((a,s)=>a+salePending(s),0));document.getElementById('reportSalesList').innerHTML=buildSalesTable(sales);document.getElementById('reportClientsList').innerHTML=buildClientTable(sales)}
function buildSalesTable(sales){if(!sales.length)return '<div class="empty-state">Sin ventas en este periodo.</div>';return `<table class="report-table"><thead><tr><th>Fecha</th><th>Cliente</th><th>Producto</th><th>Cant.</th><th>Pollitos</th><th>Transporte</th><th>Total</th><th>Costo</th><th>Ganancia</th><th>Cobrado</th><th>Pendiente</th></tr></thead><tbody>${[...sales].sort((a,b)=>new Date(b.date)-new Date(a.date)).map(s=>`<tr><td>${fmtDate(s.date)}</td><td>${clientName(s.clientId,s)}</td><td>${productName(s.productId)}</td><td>${s.qty}</td><td>${money(saleSubtotal(s))}</td><td>${money(saleTransport(s))}</td><td>${money(saleTotal(s))}</td><td>${money(saleCost(s))}</td><td>${money(saleProfit(s))}</td><td>${money(salePaid(s))}</td><td>${money(salePending(s))}</td></tr>`).join('')}</tbody></table>`}
function clientRows(sales){const map=new Map();sales.forEach(s=>{const k=s.clientId||'__none';const r=map.get(k)||{name:clientName(s.clientId,s),sales:0,units:0,total:0,paid:0,pending:0};r.sales++;r.units+=Number(s.qty);r.total+=saleTotal(s);r.paid+=salePaid(s);r.pending+=salePending(s);map.set(k,r)});return [...map.values()].sort((a,b)=>b.total-a.total)}
function buildClientTable(sales){const rows=clientRows(sales);if(!rows.length)return '<div class="empty-state">Sin datos de clientes.</div>';return `<table class="report-table"><thead><tr><th>Cliente</th><th>Ventas</th><th>Unidades</th><th>Total</th><th>Cobrado</th><th>Pendiente</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.name}</td><td>${r.sales}</td><td>${r.units}</td><td>${money(r.total)}</td><td>${money(r.paid)}</td><td>${money(r.pending)}</td></tr>`).join('')}</tbody></table>`}
async function exportPdf(){
  if(!window.jspdf?.jsPDF)return toast('No se pudo cargar el generador de PDF');
  const sales=reportSales(),clients=clientRows(sales),[from,to]=reportRange();
  const {jsPDF}=window.jspdf;
  const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});
  try{
    const img=await fetch('assets/logo.png').then(r=>r.blob()).then(blob=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)}));
    doc.addImage(img,'PNG',14,10,30,30);
  }catch{}
  doc.setFontSize(18);doc.text('Reporte de ventas',50,18);
  doc.setFontSize(11);doc.text(`Pollitos Bebes Cespedes 069 · ${dateOnly(from)} al ${dateOnly(to)}`,50,25);
  const total=sales.reduce((a,s)=>a+saleTotal(s),0),transport=sales.reduce((a,s)=>a+saleTransport(s),0),cost=sales.reduce((a,s)=>a+saleCost(s),0),profit=sales.reduce((a,s)=>a+saleProfit(s),0),paid=sales.reduce((a,s)=>a+salePaid(s),0),pending=sales.reduce((a,s)=>a+salePending(s),0),units=sales.reduce((a,s)=>a+Number(s.qty),0);
  const boxes=[['Ventas',money(total)],['Unidades',String(units)],['Cobrado',money(paid)],['Pendiente',money(pending)]];
  boxes.forEach((b,i)=>{const x=50+i*56;doc.roundedRect(x,30,51,18,2,2);doc.setFontSize(8);doc.text(b[0],x+3,36);doc.setFontSize(11);doc.text(b[1],x+3,43)});
  doc.setFontSize(9);doc.text(`Transporte: ${money(transport)}   Costo: ${money(cost)}   Ganancia: ${money(profit)}`,50,54);
  doc.setFontSize(13);doc.text('Ventas',14,64);
  doc.autoTable({startY:68,head:[['Fecha','Cliente','Producto','Cant.','Pollitos','Transporte','Total','Costo','Ganancia','Cobrado','Pendiente']],body:[...sales].sort((a,b)=>new Date(b.date)-new Date(a.date)).map(s=>[fmtDate(s.date),clientName(s.clientId,s),productName(s.productId),s.qty,money(saleSubtotal(s)),money(saleTransport(s)),money(saleTotal(s)),money(saleCost(s)),money(saleProfit(s)),money(salePaid(s)),money(salePending(s))]),styles:{fontSize:7}});
  let y=doc.lastAutoTable.finalY+8;doc.setFontSize(13);doc.text('Clientes',14,y);
  doc.autoTable({startY:y+3,head:[['Cliente','Ventas','Unidades','Total','Cobrado','Pendiente']],body:clients.map(r=>[r.name,r.sales,r.units,money(r.total),money(r.paid),money(r.pending)]),styles:{fontSize:8}});
  y=doc.lastAutoTable.finalY+8;doc.setFontSize(13);doc.text('Inventario actual',14,y);
  doc.autoTable({startY:y+3,head:[['Producto','Disponible','Precio']],body:state.products.map(p=>[p.name,p.stock,money(p.price)]),styles:{fontSize:8}});
  y=doc.lastAutoTable.finalY+8;if(y>190){doc.addPage();y=15}doc.setFontSize(13);doc.text('Efectivo actual',14,y);doc.setFontSize(11);doc.text(`${money(cashTotal())} registrado por denominaciones.`,14,y+7);
  doc.save(`reporte-pollitos-${dateOnly(from)}-${dateOnly(to)}.pdf`);
  toast('PDF descargado');
}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function renderAll(){renderDashboard();renderHistory();renderClients();renderInventory();renderMoney();renderProducts();renderSaleSelectors();renderSaleCash();if(document.getElementById('view-reports').classList.contains('active'))renderReports()}

document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.close).close()));
document.getElementById('saleProduct').addEventListener('change',e=>{const p=productById(e.target.value);if(p&&!document.getElementById('saleId').value)document.getElementById('salePrice').value=p.price;updateSalePreview();updateStockHint()});['saleQty','salePrice','saleTransport'].forEach(id=>document.getElementById(id).addEventListener('input',updateSalePreview));document.getElementById('salePaid').addEventListener('input',renderSaleCash);document.getElementById('salePayment').addEventListener('change',()=>{if(document.getElementById('salePayment').value!=='cash')saleCashCounts={};renderSaleCash()});
document.getElementById('saleForm').addEventListener('submit',e=>{e.preventDefault();const id=document.getElementById('saleId').value,productId=document.getElementById('saleProduct').value,qty=Number(document.getElementById('saleQty').value),price=Number(document.getElementById('salePrice').value),transport=Number(document.getElementById('saleTransport').value||0),total=qty*price+transport,paid=Number(document.getElementById('salePaid').value),payment=document.getElementById('salePayment').value,product=productById(productId);if(!product)return toast('Selecciona un producto');let available=Number(product.stock||0);const old=id?state.sales.find(s=>s.id===id):null;if(old&&old.productId===productId)available+=Number(old.qty);if(qty>available)return toast(`Inventario insuficiente. Disponible: ${available}`);if(qty<=0||price<0||transport<0||paid<0||paid>total)return toast('Revisa cantidad, precio, transporte y monto recibido');if(payment==='cash'&&paid>0&&Math.abs(saleCashAmount()-paid)>.01)return toast('Las denominaciones deben sumar exactamente el monto recibido');if(old){const oldProduct=productById(old.productId);if(oldProduct)oldProduct.stock+=Number(old.qty);applyCashMap(cashMapFromSale(old),-1)}product.stock-=qty;const selectedClientId=document.getElementById('saleCustomer').value;const cashDenominations=payment==='cash'&&paid>0?Object.fromEntries(Object.entries(saleCashCounts).filter(([,c])=>Number(c)>0).map(([v,c])=>[v,Number(c)])):{};const data={id:id||uid(),clientId:selectedClientId,clientSnapshot:selectedClientId?(clientById(selectedClientId)?.name||old?.clientSnapshot||''):'',productId,qty,price,transport,costPriceSnapshot:old?.costPriceSnapshot??Number(product.costPrice||0),paid,payment,cashDenominations,note:document.getElementById('saleNote').value.trim(),date:old?.date||new Date().toISOString()};applyCashMap(cashDenominations,1);if(id)state.sales[state.sales.findIndex(s=>s.id===id)]=data;else state.sales.push(data);queueDatabaseSave();e.target.reset();document.getElementById('saleId').value='';saleCashCounts={};toast('Venta guardada con transporte y rentabilidad');go('dashboard');renderAll()});
document.getElementById('historySearch').addEventListener('input',renderHistory);document.getElementById('historyFilter').addEventListener('change',renderHistory);document.getElementById('clientSearch').addEventListener('input',renderClients);
function openClient(c=null){document.getElementById('clientId').value=c?.id||'';document.getElementById('clientName').value=c?.name||'';document.getElementById('clientPhone').value=c?.phone||'';document.getElementById('clientDialogTitle').textContent=c?'Editar cliente':'Nuevo cliente';document.getElementById('clientDialog').showModal()}
document.getElementById('addClientBtn').onclick=()=>{clientDialogSource='clients';openClient()};document.getElementById('quickClientBtn').onclick=()=>{clientDialogSource='sale';openClient()};document.getElementById('clientForm').addEventListener('submit',e=>{e.preventDefault();const id=document.getElementById('clientId').value,data={id:id||uid(),name:document.getElementById('clientName').value.trim(),phone:document.getElementById('clientPhone').value.trim()};if(!data.name)return toast('Escribe el nombre del cliente');if(id){state.clients[state.clients.findIndex(c=>c.id===id)]=data;state.sales.forEach(s=>{if(String(s.clientId)===String(id))s.clientSnapshot=data.name})}else state.clients.push(data);save();if(clientDialogSource==='sale'){renderSaleSelectors();document.getElementById('saleCustomer').value=data.id}clientDialogSource='clients';document.getElementById('clientDialog').close();toast('Cliente guardado')});
function openProduct(p=null){document.getElementById('productId').value=p?.id||'';document.getElementById('productName').value=p?.name||'';document.getElementById('productPrice').value=p?.price??50;document.getElementById('productCost').value=p?.costPrice??0;document.getElementById('productDialog').showModal()}
document.getElementById('addProductBtn').onclick=()=>openProduct();document.getElementById('productForm').addEventListener('submit',e=>{e.preventDefault();const id=document.getElementById('productId').value;const old=id?productById(id):null;const data={id:id||uid(),name:document.getElementById('productName').value.trim(),price:Number(document.getElementById('productPrice').value),costPrice:Number(document.getElementById('productCost').value),stock:Number(old?.stock||0)};if(id)state.products[state.products.findIndex(p=>p.id===id)]=data;else state.products.push(data);save();document.getElementById('productDialog').close();toast('Producto guardado')});
document.getElementById('addStockBtn').onclick=()=>{renderInventory();document.getElementById('stockQty').value='';document.getElementById('stockCost').value=productById(document.getElementById('stockProduct').value)?.costPrice||0;document.getElementById('stockNote').value='';document.getElementById('stockDialog').showModal()};document.getElementById('stockForm').addEventListener('submit',e=>{e.preventDefault();const productId=document.getElementById('stockProduct').value,qty=Number(document.getElementById('stockQty').value),costPrice=Number(document.getElementById('stockCost').value),p=productById(productId);if(!p||qty<=0||costPrice<0)return toast('Revisa cantidad y costo de compra');p.stock+=qty;p.costPrice=costPrice;state.stockMovements.push({id:uid(),productId,qty,costPrice,totalCost:qty*costPrice,note:document.getElementById('stockNote').value.trim(),date:new Date().toISOString()});save();document.getElementById('stockDialog').close();toast('Compra e inventario registrados')});
document.getElementById('view-money').addEventListener('input',e=>{if(e.target.dataset.denom!==undefined){const i=Number(e.target.dataset.denom);state.denominations[i].count=Math.max(0,Math.floor(Number(e.target.value||0)));queueDatabaseSave();renderMoney();renderDashboard()}});document.getElementById('resetDenomsBtn').onclick=()=>{if(confirm('¿Limpiar todas las cantidades de billetes y monedas?')){state.denominations.forEach(d=>d.count=0);save()}};
document.getElementById('stockEditForm').addEventListener('submit',e=>{e.preventDefault();const id=document.getElementById('stockEditProductId').value,p=productById(id),next=Math.max(0,Math.floor(Number(document.getElementById('stockEditQty').value||0)));if(!p)return;const previous=Number(p.stock||0),diff=next-previous;p.stock=next;if(diff!==0)state.stockMovements.push({id:uid(),productId:id,qty:diff,note:`Ajuste manual: ${previous} → ${next}`,date:new Date().toISOString()});save();document.getElementById('stockEditDialog').close();toast('Cantidad actualizada')});
document.getElementById('view-money').addEventListener('click',e=>{const t=e.target;if(t.dataset.denomPlus!==undefined||t.dataset.denomMinus!==undefined){const i=Number(t.dataset.denomPlus??t.dataset.denomMinus),delta=t.dataset.denomPlus!==undefined?1:-1;state.denominations[i].count=Math.max(0,Number(state.denominations[i].count||0)+delta);save()}});
document.getElementById('saleCashSection').addEventListener('input',e=>{if(e.target.dataset.saleDenom!==undefined){const value=Number(e.target.dataset.saleDenom);saleCashCounts[value]=Math.max(0,Math.floor(Number(e.target.value||0)));renderSaleCash()}});document.getElementById('saleCashSection').addEventListener('click',e=>{const t=e.target;if(t.dataset.saleDenomPlus!==undefined||t.dataset.saleDenomMinus!==undefined){const value=Number(t.dataset.saleDenomPlus??t.dataset.saleDenomMinus),delta=t.dataset.saleDenomPlus!==undefined?1:-1;saleCashCounts[value]=Math.max(0,Number(saleCashCounts[value]||0)+delta);renderSaleCash()}});document.getElementById('clearSaleCashBtn').onclick=()=>{saleCashCounts={};renderSaleCash()};
document.body.addEventListener('click',e=>{const t=e.target;if(t.dataset.editStock){const p=productById(t.dataset.editStock);document.getElementById('stockEditProductId').value=p.id;document.getElementById('stockEditProductName').textContent=p.name;document.getElementById('stockEditQty').value=p.stock;document.getElementById('stockEditDialog').showModal()}if(t.dataset.stockPlus||t.dataset.stockMinus){const id=t.dataset.stockPlus||t.dataset.stockMinus,p=productById(id),delta=t.dataset.stockPlus?1:-1;if(p&&p.stock+delta>=0){p.stock+=delta;state.stockMovements.push({id:uid(),productId:id,qty:delta,note:'Ajuste rápido',date:new Date().toISOString()});save()}}if(t.dataset.editSale){const s=state.sales.find(x=>x.id===t.dataset.editSale);if(!s)return;go('sale');document.getElementById('saleId').value=s.id;document.getElementById('saleCustomer').value=s.clientId;document.getElementById('saleProduct').value=s.productId;document.getElementById('saleQty').value=s.qty;document.getElementById('salePrice').value=s.price;document.getElementById('saleTransport').value=s.transport||0;document.getElementById('salePaid').value=s.paid;document.getElementById('salePayment').value=s.payment;saleCashCounts=cashMapFromSale(s);document.getElementById('saleNote').value=s.note||'';updateSalePreview();updateStockHint();renderSaleCash()}if(t.dataset.delSale&&confirm('¿Eliminar esta venta? El inventario será devuelto.')){const s=state.sales.find(x=>x.id===t.dataset.delSale);const p=productById(s?.productId);if(p)p.stock+=Number(s.qty);applyCashMap(cashMapFromSale(s),-1);state.sales=state.sales.filter(s=>s.id!==t.dataset.delSale);state.payments=state.payments.filter(p=>p.saleId!==t.dataset.delSale);save();toast('Venta eliminada')}if(t.dataset.pay){const s=state.sales.find(x=>x.id===t.dataset.pay),p=salePending(s);document.getElementById('paymentSaleId').value=s.id;document.getElementById('paymentPendingLabel').textContent='Pendiente: '+money(p);document.getElementById('paymentAmount').value=p;document.getElementById('paymentAmount').max=p;document.getElementById('paymentDialog').showModal()}if(t.dataset.editClient)openClient(clientById(t.dataset.editClient));if(t.dataset.delClient){if(state.sales.some(s=>s.clientId===t.dataset.delClient))return toast('Este cliente tiene ventas registradas');if(confirm('¿Eliminar cliente?')){state.clients=state.clients.filter(c=>c.id!==t.dataset.delClient);save()}}if(t.dataset.editProduct)openProduct(productById(t.dataset.editProduct));if(t.dataset.delProduct){if(state.sales.some(s=>s.productId===t.dataset.delProduct)||productById(t.dataset.delProduct)?.stock>0)return toast('No puedes eliminarlo si tiene ventas o inventario');if(confirm('¿Eliminar tipo de pollito?')){state.products=state.products.filter(p=>p.id!==t.dataset.delProduct);save()}}});
document.getElementById('paymentForm').addEventListener('submit',e=>{e.preventDefault();const saleId=document.getElementById('paymentSaleId').value,s=state.sales.find(x=>x.id===saleId),amount=Number(document.getElementById('paymentAmount').value),pending=salePending(s);if(amount<=0||amount>pending)return toast('Monto inválido');state.payments.push({id:uid(),saleId,amount,method:document.getElementById('paymentMethod').value,date:new Date().toISOString()});save();document.getElementById('paymentDialog').close();toast('Abono registrado')});
document.getElementById('reportPeriod').addEventListener('change',e=>{document.getElementById('customDates').classList.toggle('hidden',e.target.value!=='custom');renderReports()});['reportFrom','reportTo'].forEach(id=>document.getElementById(id).addEventListener('change',renderReports));document.getElementById('exportPdfBtn').onclick=exportPdf;
document.getElementById('backupBtn').onclick=()=>downloadBlob(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),`respaldo-pollitos-${todayKey()}.json`);document.getElementById('restoreInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!Array.isArray(data.sales)||!Array.isArray(data.products))throw 0;if(confirm('Esto reemplazará los datos actuales. ¿Continuar?')){state={...structuredClone(defaults),...data};state.products=state.products.map(p=>({...p,stock:Number(p.stock||0),costPrice:Number(p.costPrice||0)}));state.stockMovements=state.stockMovements||[];save();toast('Respaldo restaurado')}}catch{toast('Archivo de respaldo inválido')}e.target.value=''});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;document.getElementById('installBtn').hidden=false});document.getElementById('installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;document.getElementById('installBtn').hidden=true}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
// Acceso del propietario con Supabase Auth.
const SUPABASE_URL='https://eawwbpglridntkorktyu.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_nH2R7mRU4jcl0DJ2GQ4-Zg_bNdo5-iS';
const OWNER_USERNAME='Cespedes19';
// Alias técnico de Auth. No es una contraseña ni una clave privada.
const OWNER_AUTH_EMAIL='cesarcespedes708@gmail.com';
const AUTH_REMEMBERED_USER='pollitos_remembered_user_v1';
const AUTH_PERSIST='pollitos_auth_persist_v1';
const authStorage={
  getItem:key=>(localStorage.getItem(AUTH_PERSIST)!=='0'?localStorage:sessionStorage).getItem(key),
  setItem:(key,value)=>(localStorage.getItem(AUTH_PERSIST)!=='0'?localStorage:sessionStorage).setItem(key,value),
  removeItem:key=>{localStorage.removeItem(key);sessionStorage.removeItem(key)}
};
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{storage:authStorage,persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});

let databaseSaveTimer=null;
let databaseReady=false;
const dbRow=(row)=>{const x={...row};delete x.user_id;delete x.created_at;delete x.updated_at;return x};
async function loadDatabaseState(){
  const {data:{user}}=await supabaseClient.auth.getUser();
  if(!user)return false;
  const tables=['products','clients','sales','payments','stock_movements','denominations'];
  const results=await Promise.all(tables.map(table=>supabaseClient.from(table).select('*').eq('user_id',user.id)));
  const failed=results.find(r=>r.error);if(failed){console.error(failed.error);toast('No se pudo cargar la base de datos');return false}
  const [products,clients,sales,payments,movements,denominations]=results.map(r=>r.data||[]);
  state={
    products:products.length?products.map(r=>({id:r.id,name:r.name,price:Number(r.price),costPrice:Number(r.cost_price),stock:Number(r.stock)})):structuredClone(defaults.products),
    clients:clients.map(r=>({id:r.id,name:r.name,phone:r.phone||'',transportCost:Number(r.transport_cost||0)})),
    sales:sales.map(r=>({id:r.id,clientId:r.client_id||'',clientSnapshot:r.client_snapshot||'',productId:r.product_id,qty:Number(r.qty),price:Number(r.price),transport:Number(r.transport||0),costPriceSnapshot:Number(r.cost_price_snapshot||0),paid:Number(r.paid||0),payment:r.payment,cashDenominations:r.cash_denominations||{},note:r.note||'',date:r.sale_date})),
    payments:payments.map(r=>({id:r.id,saleId:r.sale_id,amount:Number(r.amount),method:r.method,date:r.payment_date})),
    stockMovements:movements.map(r=>({id:r.id,productId:r.product_id,qty:Number(r.qty),costPrice:r.cost_price===null?undefined:Number(r.cost_price),totalCost:r.total_cost===null?undefined:Number(r.total_cost),note:r.note||'',date:r.movement_date})),
    denominations:denominations.length?denominations.sort((a,b)=>Number(a.value)-Number(b.value)).map(r=>({value:Number(r.value),count:Number(r.count)})):structuredClone(defaults.denominations)
  };
  databaseReady=true;renderAll();
  const isEmpty=!products.length&&!clients.length&&!sales.length&&!payments.length&&!movements.length&&!denominations.length;
  if(isEmpty)await saveDatabaseState();
  return true
}
async function syncTable(table,rows,userId){
  const {data:existing,error:e1}=await supabaseClient.from(table).select('id').eq('user_id',userId);if(e1)throw e1;
  const ids=new Set(rows.map(r=>String(r.id)));const remove=(existing||[]).filter(r=>!ids.has(String(r.id))).map(r=>r.id);
  if(remove.length){const {error}=await supabaseClient.from(table).delete().eq('user_id',userId).in('id',remove);if(error)throw error}
  if(rows.length){const {error}=await supabaseClient.from(table).upsert(rows,{onConflict:'id'});if(error)throw error}
}
async function saveDatabaseState(){
  if(!databaseReady)return;
  const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return;const u=user.id;
  try{
    await syncTable('products',state.products.map(p=>({id:String(p.id),user_id:u,name:p.name,price:Number(p.price||0),cost_price:Number(p.costPrice||0),stock:Number(p.stock||0)})),u);
    await syncTable('clients',state.clients.map(c=>({id:String(c.id),user_id:u,name:c.name,phone:c.phone||'',transport_cost:Number(c.transportCost||0)})),u);
    await syncTable('sales',state.sales.map(s=>({id:String(s.id),user_id:u,client_id:s.clientId||null,client_snapshot:s.clientSnapshot||'',product_id:String(s.productId),qty:Number(s.qty),price:Number(s.price),transport:Number(s.transport||0),cost_price_snapshot:Number(s.costPriceSnapshot||0),paid:Number(s.paid||0),payment:s.payment||'cash',cash_denominations:s.cashDenominations||{},note:s.note||'',sale_date:s.date})),u);
    await syncTable('payments',state.payments.map(p=>({id:String(p.id),user_id:u,sale_id:String(p.saleId),amount:Number(p.amount),method:p.method||'cash',payment_date:p.date})),u);
    await syncTable('stock_movements',state.stockMovements.map(m=>({id:String(m.id),user_id:u,product_id:String(m.productId),qty:Number(m.qty),cost_price:m.costPrice===undefined?null:Number(m.costPrice),total_cost:m.totalCost===undefined?null:Number(m.totalCost),note:m.note||'',movement_date:m.date})),u);
    const denomRows=state.denominations.map(d=>({id:String(d.value),user_id:u,value:Number(d.value),count:Number(d.count||0)}));await syncTable('denominations',denomRows,u);
  }catch(error){console.error(error);toast('No se pudieron guardar los cambios en la nube')}
}
function queueDatabaseSave(){clearTimeout(databaseSaveTimer);databaseSaveTimer=setTimeout(saveDatabaseState,250)}

function setAuthVisible(show){const screen=document.getElementById('authScreen');document.body.classList.toggle('auth-locked',show);screen?.classList.toggle('is-hidden',!show)}
function authShake(id,msg){const el=document.getElementById(id),card=document.querySelector('.auth-card');el.textContent=msg;card.classList.remove('auth-shake');void card.offsetWidth;card.classList.add('auth-shake')}
function showLogin(){
  const login=document.getElementById('loginForm'),setup=document.getElementById('setupForm'),remembered=localStorage.getItem(AUTH_REMEMBERED_USER)||'';
  setup.classList.add('hidden');login.classList.remove('hidden');
  document.getElementById('authSubtitle').textContent='Hola César. Ingresa para continuar.';
  if(remembered){document.getElementById('loginUser').value=remembered;document.getElementById('rememberUser').checked=true}
  setAuthVisible(true);setTimeout(()=>document.getElementById(remembered?'loginPassword':'loginUser')?.focus(),80)
}
document.getElementById('loginForm').addEventListener('submit',async e=>{
  e.preventDefault();
  const userInput=document.getElementById('loginUser').value.trim(),pass=document.getElementById('loginPassword').value;
  if(userInput.toLocaleLowerCase()!==OWNER_USERNAME.toLocaleLowerCase())return authShake('loginError','Usuario o contraseña incorrectos.');
  localStorage.setItem(AUTH_PERSIST,document.getElementById('rememberLogin').checked?'1':'0');
  if(document.getElementById('rememberUser').checked)localStorage.setItem(AUTH_REMEMBERED_USER,userInput);else localStorage.removeItem(AUTH_REMEMBERED_USER);
  const {error}=await supabaseClient.auth.signInWithPassword({email:OWNER_AUTH_EMAIL,password:pass});
  if(error)return authShake('loginError','Usuario o contraseña incorrectos.');
  const loaded=await loadDatabaseState();
  if(!loaded)return authShake('loginError','No se pudo conectar con la base de datos.');
  document.getElementById('loginError').textContent='';document.getElementById('loginPassword').value='';setAuthVisible(false)
});
document.querySelectorAll('[data-toggle-password]').forEach(btn=>btn.addEventListener('click',()=>{const input=document.getElementById(btn.dataset.togglePassword);input.type=input.type==='password'?'text':'password';btn.textContent=input.type==='password'?'◉':'⊘'}));
document.getElementById('logoutBtn')?.addEventListener('click',async()=>{if(confirm('¿Cerrar sesión en este dispositivo?')){await supabaseClient.auth.signOut();document.getElementById('loginPassword').value='';showLogin()}});
(async()=>{const {data:{session}}=await supabaseClient.auth.getSession();if(session){await loadDatabaseState();setAuthVisible(false)}else showLogin()})();
supabaseClient.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||!session)showLogin()});

renderAll();prepareSale();


// Entrada visual breve: mantiene la app rápida y respeta reducción de movimiento.
(function(){
  const splash=document.getElementById('appSplash');
  if(!splash){document.body.classList.remove('is-loading');return}
  const reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const closeSplash=()=>{splash.classList.add('hide');document.body.classList.remove('is-loading');setTimeout(()=>splash.remove(),550)};
  if(reduced){setTimeout(closeSplash,120);return}
  const firstThisSession=!sessionStorage.getItem('pollitosSplashSeen');
  sessionStorage.setItem('pollitosSplashSeen','1');
  setTimeout(closeSplash,firstThisSession?1450:520);
})();
